In [1]:
import torch

In [4]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
b = torch.tensor([[3,4,5],[2,5,5],[4,3,2]])

In [5]:
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
b

tensor([[3, 4, 5],
        [2, 5, 5],
        [4, 3, 2]])

In [10]:
res = torch.zeros([3,3])
res

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        for k in range(b.shape[1]):
            res[i][j] += a[i][k] * b[k][j]

In [15]:
for i in range(a.shape[0]):
    print()
    for j in range(b.shape[0]):
        print(res[i][j].item(), end = ' ')


19.0 23.0 21.0 
46.0 59.0 57.0 
73.0 95.0 93.0 