In [10]:
import torch
import numpy as np

In [7]:
torch.ones([2,3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.zeros([2,3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.tensor(range(2,10))

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
z = np.array([2,3,4,5])
torch.tensor(z)

tensor([2, 3, 4, 5], dtype=torch.int32)

In [15]:
torch.tensor(12).item()

12

In [26]:
a = torch.tensor([1.,2.,345.,654.], dtype=float)
b = torch.tensor([53,2323,4535,563], dtype=float)

In [22]:
a + b

tensor([  54., 2325., 4880., 1217.], dtype=torch.float64)

In [23]:
a - b

tensor([  -52., -2321., -4190.,    91.], dtype=torch.float64)

In [24]:
a * b

tensor([5.3000e+01, 4.6460e+03, 1.5646e+06, 3.6820e+05], dtype=torch.float64)

In [27]:
b.mean()

tensor(1868.5000, dtype=torch.float64)

In [28]:
b.std()

tensor(2026.2579, dtype=torch.float64)

In [29]:
torch.randn(1,1)

tensor([[1.4131]])